<script lang="ts">
	/**
	 * A root system, drawn downward from a single crown.
	 *
	 * Generated by recursive bifurcation with a deterministic pseudo-random
	 * source, so it branches like a root rather than like a symmetrical tree
	 * diagram — and renders identically on server and client, which a
	 * Math.random() version would not (hydration mismatch).
	 *
	 * "Built from the ground up" is the brand line; this is that line as an image.
	 */
	let {
		opacity = 0.14,
		depth = 7,
		class: klass = ''
	}: { opacity?: number; depth?: number; class?: string } = $props();

	/** Deterministic PRNG — same output every render, server and browser. */
	function makeRandom(seed: number) {
		let s = seed >>> 0;
		return () => {
			s = (s * 1664525 + 1013904223) >>> 0;
			return s / 4294967296;
		};
	}

	type Seg = { x1: number; y1: number; x2: number; y2: number; w: number };

	function grow(): Seg[] {
		const rand = makeRandom(20260924);
		const segs: Seg[] = [];

		function branch(x: number, y: number, angle: number, length: number, level: number) {
			if (level > depth || length < 3) return;
			const spread = 0.42 + rand() * 0.3;
			const x2 = x + Math.sin(angle) * length;
			const y2 = y + Math.cos(angle) * length;
			segs.push({ x1: x, y1: y, x2, y2, w: Math.max(0.4, (depth - level) * 0.42) });

			// Roots fork in two, occasionally three, and thin as they go.
			const forks = rand() > 0.78 ? 3 : 2;
			for (let i = 0; i < forks; i++) {
				const drift = (i - (forks - 1) / 2) * spread + (rand() - 0.5) * 0.24;
				branch(x2, y2, angle + drift, length * (0.66 + rand() * 0.16), level + 1);
			}
		}

		branch(200, 4, 0, 46, 1);
		return segs;
	}

	const segments = grow();
</script>

<svg
	class="pointer-events-none absolute inset-0 size-full {klass}"
	viewBox="0 0 400 300"
	preserveAspectRatio="xMidYMin slice"
	aria-hidden="true"
	focusable="false"
	style:opacity
>
	{#each segments as s, i (i)}
		<line
			x1={s.x1.toFixed(2)}
			y1={s.y1.toFixed(2)}
			x2={s.x2.toFixed(2)}
			y2={s.y2.toFixed(2)}
			stroke="currentColor"
			stroke-width={s.w.toFixed(2)}
			stroke-linecap="round"
		/>
	{/each}
</svg>
