import { error, fail, redirect } from '@sveltejs/kit';
import type { Actions, PageServerLoad } from './$types';
import { cartRepository } from '$lib/server/cart';
import {
	checkoutKeyId,
	mockWebhookDelivery,
	paymentProviderName,
	verifyRedirect
} from '$lib/server/payments';

/**
 * §04 — the redirect-versus-webhook race, handled rather than hoped away.
 *
 * Razorpay sends the customer back to the browser at roughly the same moment
 * it posts the webhook, and the two arrive in no fixed order. A page that
 * trusted the redirect would mark orders paid that were never captured; a page
 * that ignored it would strand the customer on a spinner. So this page does
 * neither: it holds the customer here and polls for the ORDER to become paid,
 * which only the webhook can do (/api/webhooks/razorpay).
 *
 * THE PAGE REQUIRES THE ORDER'S PUBLIC TOKEN. Never the id, never the order
 * number: both are guessable or sequential, and this screen shows an address.
 * `public_token` is 24 random bytes generated by app.commit_order().
 */

export const load: PageServerLoad = async ({ url }) => {
	const token = url.searchParams.get('order');
	// No token means no capability to see this order. Not a redirect to a
	// friendlier page — there is nothing here to be friendly about.
	if (!token) error(400, "We couldn't find that order.");

	const order = await cartRepository.findOrderByToken(token);
	if (!order) error(404, "We couldn't find that order.");

	// Paid already: the webhook won the race, or the customer came back later.
	if (order.state !== 'pending_payment') redirect(303, `/order/${order.publicToken}`);

	const intent = await cartRepository.findPaymentIntent({ orderId: order.id });

	return {
		order: {
			publicToken: order.publicToken,
			orderNumber: order.orderNumber,
			state: order.state,
			total: order.total,
			email: order.email,
			/** Handed to Razorpay so it does not ask again for what we already have. */
			name: order.ship.name,
			phone: order.ship.phone
		},
		payment: {
			name: paymentProviderName(),
			/** Present once a gateway order exists; null when payment is not wired. */
			gatewayOrderId: intent?.gatewayOrderId ?? null,
			/** The gateway's own figure for the intent, which is what the modal charges. */
			amount: intent?.amount ?? order.total,
			/** Publishable only; null under the mock. */
			keyId: checkoutKeyId()
		}
	};
};

export const actions: Actions = {
	/**
	 * The Razorpay modal's success payload. Verified so the page can say
	 * "payment received" honestly; the order stays pending until the webhook.
	 */
	verifyPayment: async ({ request }) => {
		const data = await request.formData();
		const token = (data.get('order') ?? '').toString();

		const order = await cartRepository.findOrderByToken(token);
		if (!order) return fail(404, { problem: "We couldn't find that order." });

		const intent = await cartRepository.findPaymentIntent({ orderId: order.id });
		const result = await verifyRedirect(data, intent);
		if (!result.ok) return fail(result.status, { problem: result.problem });

		// Razorpay itself says captured: settle now, through the same idempotent
		// capture the webhook uses, so the customer is not left waiting on it.
		if (result.captured) {
			await cartRepository.capturePayment(result.captured).catch((cause) => {
				console.error('[checkout] capture after verify failed', cause);
			});
		}

		return { verified: true };
	},

	/**
	 * The stand-in gateway settling a payment.
	 *
	 * It deliberately posts a SIGNED BODY to the real webhook route rather than
	 * calling the repository directly. §04 says the webhook is the source of
	 * truth; a "mark it paid" shortcut would leave the one path that matters
	 * untested, and the raw-body reading, the HMAC check and the event-id
	 * dedupe would all be dead code until launch day.
	 *
	 * Refused outright unless the mock provider is selected.
	 */
	settleMock: async ({ request, fetch }) => {
		if (paymentProviderName() !== 'mock') {
			return fail(403, { problem: "Test payments aren't available here." });
		}

		const data = await request.formData();
		const token = (data.get('order') ?? '').toString();

		const order = await cartRepository.findOrderByToken(token);
		if (!order) return fail(404, { problem: "We couldn't find that order." });

		const intent = await cartRepository.findPaymentIntent({ orderId: order.id });
		if (!intent) return fail(409, { problem: "There's no payment due on this order." });

		const delivery = await mockWebhookDelivery({
			gatewayOrderId: intent.gatewayOrderId,
			amount: intent.amount
		});

		const response = await fetch('/api/webhooks/razorpay', {
			method: 'POST',
			headers: {
				'content-type': 'application/json',
				// The same two headers the live gateway sends, so the route does
				// not learn a second shape it will never see in production.
				'x-razorpay-signature': delivery.signature,
				'x-razorpay-event-id': delivery.eventId
			},
			body: delivery.body
		});

		if (!response.ok) {
			return fail(502, { problem: `The test payment didn't go through (${response.status}). Please try again.` });
		}

		return { settled: true };
	}
};
