import { error, fail, redirect } from '@sveltejs/kit';
import type { Actions, PageServerLoad } from './$types';
import { cartRepository } from '$lib/server/cart';
import { mockWebhookDelivery, paymentProviderName } from '$lib/server/payments';

/**
 * §04 — the redirect-versus-webhook race, handled rather than hoped away.
 *
 * Razorpay sends the customer back to the browser at roughly the same moment
 * it posts the webhook, and the two arrive in no fixed order. A page that
 * trusted the redirect would mark orders paid that were never captured; a page
 * that ignored it would strand the customer on a spinner. So this page does
 * neither: it holds the customer here and polls for the ORDER to become paid,
 * which only the webhook can do (/api/webhooks/razorpay).
 *
 * THE PAGE REQUIRES THE ORDER'S PUBLIC TOKEN. Never the id, never the order
 * number: both are guessable or sequential, and this screen shows an address.
 * `public_token` is 24 random bytes generated by app.commit_order().
 */

export const load: PageServerLoad = async ({ url }) => {
	const token = url.searchParams.get('order');
	// No token means no capability to see this order. Not a redirect to a
	// friendlier page — there is nothing here to be friendly about.
	if (!token) error(400, 'This page needs an order reference.');

	const order = await cartRepository.findOrderByToken(token);
	if (!order) error(404, 'We have no order with that reference.');

	// Paid already: the webhook won the race, or the customer came back later.
	if (order.state !== 'pending_payment') redirect(303, `/order/${order.publicToken}`);

	const intent = await cartRepository.findPaymentIntent({ orderId: order.id });

	return {
		order: {
			publicToken: order.publicToken,
			orderNumber: order.orderNumber,
			state: order.state,
			total: order.total,
			email: order.email
		},
		payment: {
			name: paymentProviderName(),
			/** Present once a gateway order exists; null when payment is not wired. */
			gatewayOrderId: intent?.gatewayOrderId ?? null
		}
	};
};

export const actions: Actions = {
	/**
	 * The stand-in gateway settling a payment.
	 *
	 * It deliberately posts a SIGNED BODY to the real webhook route rather than
	 * calling the repository directly. §04 says the webhook is the source of
	 * truth; a "mark it paid" shortcut would leave the one path that matters
	 * untested, and the raw-body reading, the HMAC check and the event-id
	 * dedupe would all be dead code until launch day.
	 *
	 * Refused outright unless the mock provider is selected.
	 */
	settleMock: async ({ request, fetch }) => {
		if (paymentProviderName() !== 'mock') {
			return fail(403, { problem: 'The live gateway settles its own payments.' });
		}

		const data = await request.formData();
		const token = (data.get('order') ?? '').toString();

		const order = await cartRepository.findOrderByToken(token);
		if (!order) return fail(404, { problem: 'We have no order with that reference.' });

		const intent = await cartRepository.findPaymentIntent({ orderId: order.id });
		if (!intent) return fail(409, { problem: 'This order has no payment to settle.' });

		const delivery = await mockWebhookDelivery({
			gatewayOrderId: intent.gatewayOrderId,
			amount: intent.amount
		});

		const response = await fetch('/api/webhooks/razorpay', {
			method: 'POST',
			headers: {
				'content-type': 'application/json',
				// The same two headers the live gateway sends, so the route does
				// not learn a second shape it will never see in production.
				'x-razorpay-signature': delivery.signature,
				'x-razorpay-event-id': delivery.eventId
			},
			body: delivery.body
		});

		if (!response.ok) {
			return fail(502, { problem: `The stand-in gateway was refused (${response.status}).` });
		}

		return { settled: true };
	}
};
